name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn
    - run: yarn start &
    - name: Scope for Javascript
      uses: undefinedlabs/scope-for-javascript-action@v1
      with:
        # Command to run your tests.
        command: yarn test
        # Command to run your cypress tests.
        command-cypress: yarn cy:run
        # URL to run the cypress tests against.
        cypress-endpoint: http://localhost:3000
        # Scope DSN
        dsn: ${{secrets.SCOPE_DSN}}
