name: Demo app tests

on: [push]

jobs:
  build:
    strategy:
      matrix:
        node-version: [10.x, 12.x, 13.x]
    env:
      SCOPE_DSN: ${{ secrets.SCOPE_DSN }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn
      - name: Start app
        run: yarn start &
      - name: Run unit tests
        run: yarn test:unit
      - name: Run e2e tests
        run: yarn test:e2e
