name: Demo app tests

on: [push]

jobs:
  build:
    env:
      SCOPE_DSN: ${{ secrets.SCOPE_DSN }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Install dependencies
        run: yarn
      - name: Start app
        run: yarn start &
      - name: Scope for Javascript
        uses: undefinedlabs/scope-for-javascript-action@v1
        with:
          dsn: ${{secrets.SCOPE_DSN}}
          jest-command: yarn test:unit
          cypress-command: yarn test:e2e
          cypress-endpoint: http://localhost:3000
